# Generated by Django 5.1 on 2024-09-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_expense_budget_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='budget_id',
            field=models.IntegerField(choices=[(1, '6-2023')], default=None),
        ),
    ]
