# Generated by Django 5.1 on 2024-09-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_expense_budget_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='budget_id',
            field=models.IntegerField(choices=[(1, '1-2024'), (10, '10-2024'), (11, '11-2024'), (12, '12-2024'), (2, '2-2024'), (3, '3-2024'), (5, '5-2024'), (13, '6-2023'), (6, '6-2024'), (7, '7-2024'), (8, '8-2024'), (9, '9-2024')], default=9),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2024-09-18'),
        ),
    ]
