# Generated by Django 5.1 on 2024-09-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_month', models.CharField(max_length=7, unique=True)),
                ('gas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('food', models.DecimalField(decimal_places=2, max_digits=6)),
                ('internet', models.DecimalField(decimal_places=2, max_digits=6)),
                ('phone', models.DecimalField(decimal_places=2, max_digits=6)),
                ('electric', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trash', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mortgage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('child_care', models.DecimalField(decimal_places=2, max_digits=6)),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField(default='2024-09-16')),
                ('merchant', models.CharField(max_length=20)),
                ('line_item', models.CharField(choices=[('gas', 'Gas'), ('food', 'Food'), ('internet', 'Internet'), ('phone', 'Phone'), ('electric', 'Electric'), ('trash', 'Trash'), ('mortgage', 'Mortgage'), ('child_care', 'Child Care'), ('insurance', 'Insurance')], default='food', max_length=20)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cash', 'Cash'), ('check', 'Check')], default='credit_card', max_length=11)),
                ('budget_id', models.IntegerField()),
            ],
        ),
    ]
