# Generated by Django 5.1 on 2024-09-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='budget_id',
            field=models.IntegerField(choices=[], default=None),
        ),
    ]
